### ISSUE TITLE
bump tokenizers to 0.6 to avoid linking OpenSSL

### ISSUE THREAD

**Issue by lavafroth** [nicksenger/candle-token-classification#1]
Firstly, thank you for the awesome library. It has saved me hours of work.

The version of `tokenizers` used here, 0.3, requires us to link OpenSSL even when we're not downloading anything. Newer versions of `tokenizers` do not require OpenSSL by default. This makes shipping static binaries a tad bit easier, so it would be beneficial to at least bump the dependency to 0.6.

Thanks again!

**Comment by nicksenger** [comment]
Hi lavafroth, I'm glad you've found this useful!

Yes I agree all the dependencies should be updated, ideally to the latest crates.io release. Feel free to open a PR, it's hard to say when I'll have time to look into this.
